services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: poodle
      POSTGRES_USER: poodle_user
      POSTGRES_PASSWORD: poodle_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poodle_user -d poodle"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_NAME=poodle
      - DB_USER=poodle_user
      - DB_PASSWORD=poodle_password
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
  media_volume:
